### ISSUE TITLE
scconfig doesn't show any modules, and wizard gives error 245, and seiscomp status returns nothing

### ISSUE THREAD

**Issue by dsheward-astro** [seiscomp-macOS/main#1]
I have followed the instructions given to install seiscomp on macOS, and after getting it installed I tried 'seiscomp status' and nothing happens - no error, nor no output. When trying to configure with scconfig, the program loads, but there are no modules displayed in the system tab, and when running the wizard, it gives "setup finished with exit code 245"

**Comment by gilcel** [comment]
Which macOS version do you use ? Intel or Apple Silicon ?
Have you updated your Xcode command line tools and your Homebrew packages ?

```
#brew update
#brew upgrade
```

Did you install "seiscomp" in your Home folder, like /Users/YOURNAME/seiscomp/bin/ and updated your PATH in .bash_profile or .bashrc ?

Even with MySQL or MariaDB not configured `scconfig` or any other binary in `~/seiscomp/bin/` should work...
I just tried it on my Mac mini M1 (macOS Sonoma 14.3.1) with 'scconfig'....

<img width="1531" alt="Screenshot 2024-02-19 at 11 25 33" src="https://github.com/seiscomp-macOS/main/assets/9282533/0d28abd9-a12d-478b-8d09-974d6fee6844">

<img width="1107" alt="Screenshot 2024-02-19 at 11 22 53" src="https://github.com/seiscomp-macOS/main/assets/9282533/b946a9b6-4369-4006-ad82-401e4004b711">

**Comment by dsheward-astro** [comment]
I am on apple silicon M3, running Sonama 14.3

I have made sure brew was up to date, and I believe my path is set correctly: 
<img width="1352" alt="Screenshot 2024-02-19 at 11 47 34" src="https://github.com/seiscomp-macOS/main/assets/56971042/e8475075-44c5-4a84-852d-f1c0c52c4c17">
<img width="1352" alt="Screenshot 2024-02-19 at 11 47 44" src="https://github.com/seiscomp-macOS/main/assets/56971042/f0fe2d88-1aac-4690-a7a1-0e15fe60e0b5">
<img width="641" alt="Screenshot 2024-02-19 at 11 49 08" src="https://github.com/seiscomp-macOS/main/assets/56971042/7205eb3e-3eec-442f-8861-8f4a96d6ec1d">

**Comment by gilcel** [comment]
Can you do a `echo $PATH` please ?
I think it's a problem with Python3.x and the installation of Anaconda, Homebrew and I see a `/Library/Frameworks...` at the end of your PATH...this could lead to small or major problems ;-)

**Comment by dsheward-astro** [comment]
<img width="641" alt="Screenshot 2024-02-19 at 12 40 45" src="https://github.com/seiscomp-macOS/main/assets/56971042/ecc84577-5494-4e39-b98b-f845ac4afe92">

**Comment by dsheward-astro** [comment]
I have removed the framework from the PATH and re-sourced, however the same behaviour occurs with scconfig

**Comment by gilcel** [comment]
Do you use BASH Shell or ZSH (default on macOS) ?
I still use BASH, so it's more an Anaconda & Homebrew problem...what does the following command output:
#which python3

Suggestion:

If you use BASH make a backup of your .bashrc or .bash_profile, then:
Disable `/Library/Frameworks/Python.framework/Versions/3.12/bin `
Disable Anaconda (Miniconda) in your PATH, and source your .bashrc resp. or restart your Mac:

Here's my PATH from .bashrc:
`echo $PATH`

```
/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/gilles/seiscomp/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:
```

**Comment by dsheward-astro** [comment]
I am on ZSH, however after disabling both the framework and anaconda, the modules are shown in scconfig. I am making progress, and can enable the majority of the modules, however the setup wizard now gives the error:

+ Running MySQL database setup script /Users/daniel/seiscomp/share/db/mysql_setup.py
/Users/daniel/seiscomp/share/db/pkexec_wrapper.sh: line 27: pkttyagent: command not found
/Users/daniel/seiscomp/share/db/pkexec_wrapper.sh: line 31: pkexec: command not found
  - Failed to setup database
error: module 'scmaster' failed to setup
* setup kernel
* setup scmaster
* setup trunk

**Comment by gilcel** [comment]
OK sounds good..."seiscomp" works with Python v3.11 (we had some trouble with Python v3.12 too).
So install Python3.11 with Hombrew:

`#brew install python@3.11`

`#which python3.11`
/opt/homebrew/bin/python3.11

However the scripts `~/seiscomp/share/db/pkexec_wrapper.sh` call BASH instead of ZSH...and since you don't have .bashrc or .bash_profile configured, so you should add at the PATH of Homebrew etc. in the .bashrc config file.

**Comment by dsheward-astro** [comment]
Hi, thanks for your help, after adding to the .bashrc path, and changing the permissions of the seiscomp directories, I am now all up an running.

**Comment by gilcel** [comment]
Ah great news...I just updated seiscomp-macos in sync with upstream seiscomp repo, which fixes the scalert app crash etc.
